# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        sudo apt install pip
        pip install pytest
        pip install pygame

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.3.0

    - name: Install dependencies
      run: |
       sudo apt-get update
       sudo apt-get install -y ruby-full
       gem install bundler
       bundle install

    - name: Set up Coveralls token
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        echo "Coveralls repo token is set"

   


    - name: Run tests and send coverage report to Coveralls
      env:
        CI: true
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        bundle exec rspec
        bundle exec coveralls --verbose

    
      

    - name: Test with pytest
      run: |
        python3 -m pytest app/test.py 
