name: Coveralls

on:
  push:
    branches: [master]

jobs:
  coveralls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage coveralls
      - name: Run tests
        run: |
          coverage run --source=your_project_name -m pytest
      - name: Coveralls
        uses: coverallsapp/github-action@v2.1.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
